import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenu, NavigationMenuItem, NavigationMenuLink, NavigationMenuList } from "@/components/ui/navigation-menu";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { Toaster } from "@/components/ui/sonner";
import { MobileNav } from "@/components/layout/MobileNav";
import { DynamicBreadcrumb } from "@/components/layout/DynamicBreadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen bg-[#f6f7e8] overflow-x-hidden">
          {/* ---------------- NAVBAR ---------------- */}
          <header className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 md:py-6 flex items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <MobileNav />
              <Link href="/" className="flex items-center gap-2 font-bold text-base md:text-lg">
                <Image
                  src="/logo.jpg"
                  alt="Chintan Chikitsa Logo"
                  width={40}
                  height={40}
                  className="w-8 h-8 md:w-10 md:h-10 rounded-md shrink-0"
                />
                <span className="hidden sm:inline">Chintan.Chikitsa</span>
              </Link>
            </div>

            <NavigationMenu className="hidden md:block">
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuLink asChild>
                    <Link href="/services">Services</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink asChild>
                    <Link href="/about">About</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink asChild>
                    <Link href="/book">Contact</Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>

            <Button asChild size="sm" className="hidden md:flex">
              <Link href="/book">Book Now</Link>
            </Button>
          </header>

          {/* ---------------- BREADCRUMB ---------------- */}
          <DynamicBreadcrumb />

          {children}
          {/* ---------------- FOOTER ---------------- */}
          <footer className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20 border-t">
            <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-8 md:gap-12">
              <div>
                <p className="large">Chintan.Chikitsa</p>
                <p className="muted">
                  Frequency Coach & Holistic Healer guiding you toward mental,
                  emotional, and spiritual harmony.
                </p>
              </div>

              <NavigationMenu>
                <NavigationMenuList className="flex-col">
                  {["Services", "About", "Contact", "Privacy"].map((link) => (
                    <NavigationMenuItem key={link}>
                      <NavigationMenuLink asChild>
                        <Link href={`/${link.toLowerCase()}`}>{link}</Link>
                      </NavigationMenuLink>
                    </NavigationMenuItem>
                  ))}
                </NavigationMenuList>
              </NavigationMenu>
            </div>
          </footer>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
